### ISSUE TITLE
glfw: potential memory leak reported by valgrind

### ISSUE THREAD

**Issue by xor256** [hexops/mach#60] opened 2021-11-01 09:56 UTC
please compile minimal example and run
`$valgrind --leak-check=full --show-reachable=yes program`

**Comment by slimsag** [comment] 2021-11-02 17:05
Thank you for filing this, will investigate

**Comment by silversquirl** [comment] 2021-11-12 10:10
@xor256 Assuming you're talking about mach-glfw, are you seeing any leaks unique to mach's wrapper? GLFW itself leaks memory on my system, so if that's what you're seeing, it should really be [reported to upstream](https://github.com/glfw/glfw/issues)

**Comment by AliChraghi** [comment] 2021-12-21 17:12
does **mach-glfw** only uses `c_allocator` or other zig's allocators are used too? because as far as i know valgrind does't detect zig memory leaks

**Comment by slimsag** [comment] 2021-12-22 01:29
@AliChraghi we use only `c_allocator` internally, but the tests use other Zig allocators.

This issue was opened quite a while ago, possibly fixed. We just need someone with Linux to run with Valgrind to confirm

**Comment by AliChraghi** [comment] 2021-12-22 06:03
i ran the very simple code example in [glfw documention](https://www.glfw.org/documentation) in C and Zig (using mach). both almost have same valgrind output. i think it's because the window close duration difference. i also found some comments on the internet, they say detected leaks are't caused by **X11 or GPU Driver** not `GLFW`
**Zig:**
```
definitely lost: 0 bytes in 0 blocks
indirectly lost: 0 bytes in 0 blocks
possibly lost: 178,039 bytes in 1,476 blocks
still reachable: 1,450,310 bytes in 1,993 blocks
suppressed: 1,700 bytes in 1 blocks
```
**C:**
```
definitely lost: 0 bytes in 0 blocks
indirectly lost: 0 bytes in 0 blocks
possibly lost: 178,311 bytes in 1,478 blocks
still reachable: 23,562,177 bytes in 4,380 blocks
suppressed: 1,700 bytes in 1 blocks
```

**Comment by slimsag** [comment] 2021-12-22 06:33
Great, thanks for checking @AliChraghi ! I'll close this, if anyone finds anything else here feel free to create a new issue!

**Closed by slimsag** 2021-12-22 06:33 UTC
Labels: bug, glfw, help-welcome
