### ISSUE TITLE
Unable to build mach-examples

### ISSUE THREAD

**Issue by Nairou** [hexops/mach#837] opened 2023-07-01 01:13 UTC
Followed the instructions on the website, did a recursive clone of the `mach-examples` repo.

```
/tmp/temp/mach-examples ❯ zig build run-core-boids
/tmp/temp/mach-examples/libs/mach/libs/core/sdk.zig:212:43: error: expected type 'Build.FileSource', found '[]const u8'
                            .source_dir = res,
                                          ^~~
/nix/store/jg1ys4g17cmc0jp07ik1bi2j2jv10phd-zig-0.11.0-dev.3892+0a6cd257b/lib/std/Build.zig:1634:24: note: union declared here
pub const FileSource = union(enum) {
                       ^~~~~
referenced by:
    install: /tmp/temp/mach-examples/libs/mach/build.zig:212:17
    build: /tmp/temp/mach-examples/build.zig:167:12
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Tried with zig versions `0.11.0-dev.3859+88284c124` and `0.11.0-dev.3892+0a6cd257b`.

**Comment by slimsag** [comment] 2023-07-01 03:10
Duplicate of https://github.com/hexops/mach/issues/825 - will be fixed soon!

**Closed by slimsag** 2023-07-01 03:10 UTC
