### ISSUE TITLE
Dusk: Support block comments

### ISSUE THREAD

**Issue by clickingbuttons** [hexops/mach#1089] opened 2023-10-26 01:34 UTC
```wgsl
/* hello */
const a: u32 = 0u;
```

```
null:1:1 error: expected global declaration, found '/'
1 │ /* hello */
```

**Comment by slimsag** [comment] 2023-10-28 00:16
Duplicate of https://github.com/hexops/mach/issues/1091

**Closed by slimsag** 2023-10-28 00:16 UTC
