### ISSUE TITLE
docs: update to reflect package manager

### ISSUE THREAD

**Issue by Nairou** [hexops/mach#861] opened 2023-07-15 21:11 UTC
Following instructions in the readme, I've added `mach_glfw` to my `build.zig.zon`, but the suggested build code gives an error:

```zig
const glfw = @import("mach_glfw");
// ...
exe.addModule("glfw", glfw.module(b));
try glfw.link(b, exe, .{});
```

```
build.zig:38:31: error: root struct of file 'build' has no member named 'module'
    exe.addModule("glfw", glfw.module(b));
                          ~~~~^~~~~~~
```

I also tried another method of including `mach_glfw` into my `build.zig`, but then get a different error:

```zig
const glfw_dep = b.dependency("mach_glfw", .{
    .target = target,
    .optimize = optimize,
});
exe.linkLibrary(glfw_dep.artifact("mach-glfw"));
exe.addModule("mach_glfw", glfw_dep.module("mach-glfw"));
```

```
/home/nairou/.cache/zig/p/1220b85a031e70eddbe1125ba5bbf64f590b175ff9fd3333693d56f920f424a1c20a/src/c.zig:1:15: error: C import failed
pub const c = @cImport({
              ^~~~~~~~
referenced by:
    c: /home/nairou/.cache/zig/p/1220b85a031e70eddbe1125ba5bbf64f590b175ff9fd3333693d56f920f424a1c20a/src/main.zig:4:27
    PlatformType: /home/nairou/.cache/zig/p/1220b85a031e70eddbe1125ba5bbf64f590b175ff9fd3333693d56f920f424a1c20a/src/main.zig:260:11
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

/home/nairou/.persist/dev/projects/prototypes/shipbuilder/zig-cache/o/347a9d8799a95898ac6015c6206374b5/cimport.h:3:10: error: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
         ^
```

I'm assuming this changed when the `upstream` folder was removed? I tried directly including glfw in my `build.zig.zon`, as is done in [mach-examples](https://github.com/hexops/mach-examples/blob/main/build.zig.zon), but that had no effect.

**Comment by Nairou** [comment] 2023-07-16 00:58
Found the answer on the [Mach Engine Discord](https://discord.com/channels/996677443681267802/1127534911860002857)

**Comment by slimsag** [comment] 2023-07-16 14:35
Thanks for filing, I will get our docs updated soon to reflect package manager usage.

**Comment by slimsag** [comment] 2023-07-17 13:48
For mach-glfw, we need to add the following:

We just finished/merged the changes to migrate us to the (experimental) package manager the past few weeks. The Zig package manager has some issues with transitively pulling in dependencies right now.

https://github.com/hexops/mach-gpu/blob/1266bd935c20d539d74390380364ec566be4eec9/build.zig#L36-L60

This^ is the function you will need to copy to your `build.zig` in order to use the latest version / package manager. Then to use it via e.g. `glfwLink(b, exe);`

This will get simplified over time, that's just the status quo today. Please note that the `xcode_frameworks.addPaths(b, step);` part there means you also need to copy this other chunk of code into your `build.zig`: https://github.com/hexops/mach-gpu/blob/1266bd935c20d539d74390380364ec566be4eec9/build.zig#L108-L216

again, this will get simplified over time as bugs in the package manager get resolved - it's a temporary solution.

Also, be sure to copy every dependency in `build.zig.zon` to your own `build.zig.zon` file: https://github.com/hexops/mach-glfw/blob/main/build.zig.zon#L5-L24 if you get any `@import` errors - that is the cause.

**Comment by Pyrdacor** [comment] 2023-07-18 19:44
Thanks for the info. I already use the zon file. I used some code from the Vulkan mach glfw example repo.

For me it is also a bit more complex as I have a lib which uses mach-glfw and my main exe uses that lib. I almost managed to setup all the build stuff but it wasn't very intuitive. But this is more about zig and not your project.

I will have a closer look at your links and try to make it work.

**Comment by slimsag** [comment] 2023-07-31 01:16
This page is now up-to-date: https://machengine.org/next/core/getting-started/

README will be updated as part of #881

**Closed by slimsag** 2023-07-31 01:16 UTC
Labels: docs

**Comment by nothke** [comment] 2023-08-01 15:58
I've followed [these instructions](https://github.com/hexops/mach/issues/861#issuecomment-1638185447) but I still can't get it working. I get a
```
no dependency named 'vulkan_headers' in 'C:\Users\nothke\AppData\Local\zig\p\1220a0b036095c2c54af347c86514ed9dab431299f0140b0e434ed119f85a976c32b\build.zig.zon'. All packages used in build.zig must be declared in this file.
```

But if I open that file, vulkan_headers are declared there and the hashes match the one in my own build.zig.zon. So, I'm not sure if this is a package manager issue or if I'm doing something wrong.

[Here's my repo](https://github.com/nothke/another-mach-glfw-attempt/blob/master/build.zig)

**Comment by slimsag** [comment] 2023-08-01 17:18
@nothke please file a new issue and I'll check out your repo and figure out what's wrong
