### ISSUE TITLE
Dusk: Support parentheses expressions

### ISSUE THREAD

**Issue by clickingbuttons** [hexops/mach#1090] opened 2023-10-27 21:10 UTC
Pretty simple to add to parser.

```diff
 fn expectParenExpr(p: *Parser) !NodeIndex {
-    _ = try p.expectToken(.paren_left);
+    const main_token = try p.expectToken(.paren_left);
     const expr = try p.expression() orelse {
         try p.errors.add(
             p.peekToken(.loc, 0),
@@ -1491,7 +1491,11 @@ fn expectParenExpr(p: *Parser) !NodeIndex {
         return error.Parsing;
     };
     _ = try p.expectToken(.paren_right);
-    return expr;
+    return try p.addNode(.{
+        .tag = .paren_expr,
+        .main_token = main_token,
+        .lhs = expr,
+    });
 }
 ```

**Comment by alichraghi** [comment] 2023-10-27 22:58
what's the point?

**Comment by slimsag** [comment] 2023-10-28 00:16
Duplicate of https://github.com/hexops/mach/issues/1091

**Closed by slimsag** 2023-10-28 00:16 UTC
