### ISSUE TITLE
Underscore vs Dash in module references

### ISSUE THREAD

**Issue by buzmeg** [hexops/mach#1227] opened 2024-07-15 02:18 UTC
What's the deal with the "_" vs "-" dichotomy in module usage?

```
    const mach_freetype_dep = b.dependency("mach_freetype", .{
        .target = target,
        .optimize = optimize,
    });
    exe.root_module.addImport("mach-freetype", mach_freetype_dep.module("mach-freetype"));
    exe.root_module.addImport("mach-harfbuzz", mach_freetype_dep.module("mach-harfbuzz"));
```

This makes things *extremely* confusing.  Is there a reason for switching from underscore in build.zig.zon to using a dash in actual source code?  Why not use the import with an underscore?

Thanks.

**Comment by slimsag** [comment] 2024-07-27 16:30
Duplicate of https://github.com/hexops/mach/issues/1157

**Closed by slimsag** 2024-07-27 16:30 UTC
Labels: bug, needs-triage
