### ISSUE TITLE
mach: cannot build triangle example with `-Drelease-(safe|fast|small)` on windows

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#651] opened 2022-12-28 14:02 UTC
```sh
$ zig build run-triangle -Drelease-fast 
error: lld-link: undefined symbol: __declspec(dllimport) _create_locale
    note: referenced by C:\Users\ali\dev\mach-examples\zig-cache\o\527d3edf3b31582c4000941a6eb04d3e\triangle.exe.lto.obj:(std::__1::__cloc())
    note: referenced by C:\Users\ali\dev\mach-examples\zig-cache\o\527d3edf3b31582c4000941a6eb04d3e\triangle.exe.lto.obj:(std::__1::locale::__imp::__imp(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long long))    
    note: referenced by C:\Users\ali\dev\mach-examples\zig-cache\o\527d3edf3b31582c4000941a6eb04d3e\triangle.exe.lto.obj:(std::__1::locale::__imp::__imp(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long long))    
    note: referenced 12 more times
error: lld-link: undefined symbol: __declspec(dllimport) _free_locale
    note: referenced by C:\Users\ali\dev\mach-examples\zig-cache\o\527d3edf3b31582c4000941a6eb04d3e\triangle.exe.lto.obj:(std::__1::codecvt<wchar_t, char, int>::~codecvt())
    note: referenced by C:\Users\ali\dev\mach-examples\zig-cache\o\527d3edf3b31582c4000941a6eb04d3e\triangle.exe.lto.obj:(std::__1::__time_put::~__time_put())
    note: referenced by C:\Users\ali\dev\mach-examples\zig-cache\o\527d3edf3b31582c4000941a6eb04d3e\triangle.exe.lto.obj:(std::__1::locale::__imp::__imp(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long long))    
    note: referenced 22 more times
```

**Comment by slimsag** [comment] 2022-12-28 22:06
Probably duplicate of https://github.com/hexops/mach/issues/597

**Closed by slimsag** 2022-12-28 22:06 UTC
