### ISSUE TITLE
linux: cannot build triangle example with `-Drelease-safe`

### ISSUE THREAD

**Issue by leroycep** [hexops/mach#597] opened 2022-10-23 19:46 UTC
The full stacktrace is here: https://gist.github.com/leroycep/c25d3aecca59b6b0e743af3a9f8db97e

Looks like it can't find a libgamemode symbol:

```
ld.lld: error: undefined symbol: internal_load_libgamemode
```

**Comment by alichraghi** [comment] 2022-10-25 14:42
this is a compiler bug, causing `internal_load_libgamemode` demoted to *extern* instead being translated as a function body. i can't reproduce it via `zig translate-c libs/gamemode/upstream/include/gamemode_client.h -Drelease-safe -lc`

**Comment by alichraghi** [comment] 2022-12-28 14:18
both cross-compiling for linux target in windows and running on WSL2 works fine (tried with both gamemode installed and uninstalled)
```
zig build run-triangle -Drelease-fast -Dtarget=native-linux
```
@leroycep are you able to reproduce this again?

**Comment by slimsag** [comment] 2022-12-28 21:07
Closing as it's likely fixed. Feel free to reopen if not.

**Comment by leroycep** [comment] 2022-12-28 21:19
Sorry, I just tried this out. I'm still getting this issue.

https://gist.github.com/leroycep/0c50689e9cdff5a044d088ab6a47bdc3

```
[geemili@renvi:~/src/3_resources/mach-examples]$ zig version
0.11.0-dev.980+601ab9a25
```

I'm on NixOS, here is the flake I'm using: https://gist.github.com/leroycep/e09479bffa198edb44982d8b47ab8614

**Comment by xdBronch** [comment] 2023-05-22 00:48
was this fixed by https://github.com/hexops/mach/pull/778? i was getting a different error that my pr fixed but they were suspected to be the same/linked. also noticed the gist OP gave mentioned LTO a few times

**Comment by slimsag** [comment] 2023-05-22 05:10
Yes, I'd assume so - will close. Let me know if you're still encountering this by filing a new issue :)

**Closed** 2023-05-22 05:10 UTC
Labels: bug, os/linux
