### ISSUE TITLE
core: 0.2.0 example on homepage fails to build on windows 11.

### ISSUE THREAD

**Issue by jhenzie** [hexops/mach#1015] opened 2023-09-20 14:26 UTC
ENVIRONMENT
- Windows 11.
- zig version: 0.12.0-dev.389+61b70778b
- mach-core: commit 9243a331a3eb0d4ba97aec7f793e60f1cf90bd8b
- Zig compiler installed with zigup

`zig build run-deferred-rendering`

Fails to compile with this stack:
```
steps [19/23] thread 26704 panic: reached unreachable code
C:\Users\jhenzie\bin\zig\0.12.0-dev.389+61b70778b\files\lib\build_runner.zig:797:36: 0x7ff6c23aece1 in workerMakeOneStep (build.exe.obj)
            .precheck_unstarted => unreachable,
                                   ^
C:\Users\jhenzie\bin\zig\0.12.0-dev.389+61b70778b\files\lib\std\Thread\Pool.zig:94:39: 0x7ff6c237e35e in runFn (build.exe.obj)
            @call(.auto, func, closure.arguments);
                                      ^
C:\Users\jhenzie\bin\zig\0.12.0-dev.389+61b70778b\files\lib\std\Thread\Pool.zig:133:18: 0x7ff6c243dd78 in worker (build.exe.obj)
            runFn(&run_node.data);
                 ^
C:\Users\jhenzie\bin\zig\0.12.0-dev.389+61b70778b\files\lib\std\Thread.zig:412:13: 0x7ff6c2402d9c in callFn__anon_15051 (build.exe.obj)
            @call(.auto, f, args);
            ^
C:\Users\jhenzie\bin\zig\0.12.0-dev.389+61b70778b\files\lib\std\Thread.zig:524:30: 0x7ff6c23ae5d4 in entryFn (build.exe.obj)
                return callFn(f, self.fn_args);
                             ^
???:?:?: 0x7ffcda21257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffcdb68aa67 in ??? (ntdll.dll)
error: the following build command failed with exit code 3:
```

I realize this is fully in the zig compiler, but perhaps the required version of the compiler is incorrect?

Same stack, thread numbers excluded, with:
- master
- 0.11.0

**Comment by alichraghi** [comment] 2023-09-20 15:18
duplicate of https://github.com/hexops/mach/issues/1012

**Comment by jhenzie** [comment] 2023-09-22 12:41
Sorry, I looked for the duplicate, closing as duplicate

**Closed** 2023-09-23 20:02 UTC
Labels: duplicate, core
